services:
  react-app:
    build:
      context: .
      dockerfile: ./.docker/prod/Dockerfile
    container_name: edu_platform_web
    restart: unless-stopped
    ports:
      - "3000:80"  # Map container port 80 to host port 3000
    volumes:
      - ./.docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom NGINX config

  # nginx:
  #   image: nginx:1.23
  #   container_name: edu_platform_web_nginx
  #   restart: unless-stopped
  #   ports:
  #     - "3000:80"  # Map container port 80 to server port 3000
  #   volumes:
  #     - react_build:/app/build
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom NGINX configuration
  #   depends_on:
  #     - react-app
